name: Update README with latest commits

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a medianoche UTC
  push:
    branches:
      - main  # O la rama principal de tu proyecto
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest commits
        run: |
          echo "## 📜 Últimos commits" > commits.md
          git log --pretty=format:"- %h - %s (%cd)" --date=short -n 10 >> commits.md

      - name: Update README
        run: |
          # Eliminar la sección de "Últimos commits" existente
          sed -i '/## 📜 Últimos commits/,$d' README.md
          # Añadir los últimos commits al README
          cat commits.md >> README.md
          rm commits.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          # Verificar si hay cambios antes de hacer commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Actualizar README con los últimos commits"
            git push
          fi
